# tasks file for apache
---
- name: Ensure that the httpd package is not installed in system
  yum:
    name: httpd
    state: absent
- name: Ensure that the httpd-tool package is not installed in system
  yum:
    name: httpd-tools
    state: absent
