<!DOCTYPE html>
<html>
<head>
  <title>Welcome to devops on AWS</title>
</head>
<body>
<h1><?php echo "This text was generated by php7"?></h1>
<h1><?php echo "This change reflected by asible pull cron job44"?></h1>
</body>
</html>
