# tasks file for php
---
- name: Install php 7 with the common packages
  yum:
    name: "{{ item }}"
    state: present
    lock_timeout: 60
  with_items:
    - php70
    - php70-gd
    - php70-imap
    - php70-mbstring
  notify: restart Apache

- name: Upload index.php file to remote web dir
  copy:
    src: index.php
    dest: /var/www/html
    owner: ec2-user
    group: ec2-user
